config/routes.rb
# -*- encoding : utf-8 -*-
EmoProjekt::Application.routes.draw do

  get "home/index"
  get "start/about"
  # get "users/new"
  # get "sessions/new"
  # get "sign_up" => "users#new", :as => "sign_up"
  # get "log_in" => "sessions#new", :as => "log_in"
  # get "log_out" => "sessions#destroy", :as => "log_out"
  get "emo_list" => "emoticons#index", :as => "emo_list"
  get "add_emo" => "emoticons#new", :as => "add_emo"




  root :to => "home#index"
  # resources :users
  # resources :sessions
  resources :emoticons


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

 
 
  match '/about',   to: 'home#about'
  match 'home' => 'home#index', :as => :welcomePage


end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/emoticon.rb
# -*- encoding : utf-8 -*-
class Emoticon < ActiveRecord::Base

scope :unreleased, where(:is_released => false)
after_initialize :default_values


    def default_values
      self.is_released ||= false
      
    end

def self.search(search)
  if search
    where('name LIKE ? or emo LIKE ?', "%#{search}%", "%#{search}%") 
  else
    scoped
  end
end

end

app/models/user.rb
class User < ActiveRecord::Base
  
  attr_accessible :email, :username, :password, :password_confirmation
  
  attr_accessor :password

  before_save :encrypt_password


  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

   def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
# -*- encoding : utf-8 -*-
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_user




  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/emoticons_controller.rb
# -*- encoding : utf-8 -*-
class EmoticonsController < ApplicationController
  # GET /emoticons
  # GET /emoticons.json
  helper_method :sort_column, :sort_direction
  def index
    @emoticons = Emoticon.search(params[:search]).order(sort_column + ' ' + sort_direction).paginate(:per_page => 10, :page => params[:page])
  end

  # GET /emoticons/1
  # GET /emoticons/1.json
  def show
    @emoticon = Emoticon.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @emoticon }
    end
  end

  # GET /emoticons/new
  # GET /emoticons/new.json
  def new
    @emoticon = Emoticon.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @emoticon }
    end
  end

  # GET /emoticons/1/edit
  def edit
    @emoticon = Emoticon.find(params[:id])
  end

  # POST /emoticons
  # POST /emoticons.json
  def create
    @emoticon = Emoticon.new(params[:emoticon])

    respond_to do |format|
      if @emoticon.save
        format.html { redirect_to @emoticon, notice: 'Emoticon was successfully created.' }
        format.json { render json: @emoticon, status: :created, location: @emoticon }
      else
        format.html { render action: "new" }
        format.json { render json: @emoticon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /emoticons/1
  # PUT /emoticons/1.json
  def update
    @emoticon = Emoticon.find(params[:id])

    respond_to do |format|
      if @emoticon.update_attributes(params[:emoticon])
        format.html { redirect_to @emoticon, notice: 'Emoticon was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @emoticon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emoticons/1
  # DELETE /emoticons/1.json
  def destroy
    @emoticon = Emoticon.find(params[:id])
    @emoticon.destroy

    respond_to do |format|
      format.html { redirect_to emoticons_url }
      format.json { head :no_content }
    end
  end

  private

  def sort_column
    params[:sort] || "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/controllers/home_controller.rb
# -*- encoding : utf-8 -*-
class HomeController < ApplicationController

	
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.authenticate(params[:email], params[:password])
  	if user
    	session[:user_id] = user.id
    	redirect_to emoticons_path, :notice => "Logged in!"
  	else
    	flash.now.alert = "Invalid email or password"
    	render "new"
  	end
  end

  def destroy
  	session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.search(params[:search])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
    
  end
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end
  def edit
     @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end
  
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id], :include => :profile)
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
# -*- encoding : utf-8 -*-
module ApplicationHelper
	def sortable(column, title = nil)
		title ||= column.titleize
		css_class = column == sort_column ? "curret #{sort_direction}" : nil
		direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
		link_to title, {:sort => column, :direction => direction}, {:class => css_class}
	end
 
end

app/helpers/emoticons_helper.rb
# -*- encoding : utf-8 -*-
module EmoticonsHelper

end

app/helpers/home_helper.rb
# -*- encoding : utf-8 -*-
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/emoticons/_emos.html.erb

<%= hidden_field_tag :sort, params[:sort] %>

<table align="center" class="table table-striped table-bordered table-hover">
  <tr>
  	<th>Emoticon</th>
  	<th><%= sortable "name" %></th>
  	<th></th>
  </tr>
<% @emoticons.each do |emoticon| %>
  <tr>
  	<% if emoticon.is_released == true %>
    <td><%= emoticon.emo %></td>
    <td><%= emoticon.name %></td>
    <td><button data-zc-copy-value = <%= emoticon.emo %>  >copy</button></td>
    <% end %> 
  </tr>
<% end %>
</table>
<div class="pagination pagination-centered ">
  <%= will_paginate @products %>
</div>


                 <h5><div align="center">There's no emoticon you're looking for? To suggest new emoticon <%= link_to "Click here!", add_emo_path, :class => "btn-small" %>
              </div><br></h5>



app/views/emoticons/_form.html.erb


<%= form_for(@emoticon) do |f| %>
  <% if @emoticon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@emoticon.errors.count, "error") %> prohibited this emoticon from being saved:</h2>

      <ul>
      <% @emoticon.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %> 


    <div class="form-emo">  
        <h1 align="center">New emoticon</h1> <br>
        <h4 align="center">Enter your emoticon here</h4>
         <%= f.text_field :emo, :placeholder => "*(O___o)*" %>
    </div>
    <div class="form-name-emo">
        <h4 align="center">Enter the name here (seperate multiple by comma)</h4>
        <%= f.text_field :name, :placeholder => "crazy, wtf" %>
    </div>
    <div style="text-align:center">
           <button class="btn btn-large btn-primary">
             Add Emoticon
           </button>
    </div>


<% end %>

app/views/emoticons/edit.html.erb
<h1>Editing emoticon</h1>

<%= render 'form' %>

<%= link_to 'Show', @emoticon %> |
<%= link_to 'Back', emoticons_path %>

app/views/emoticons/index.html.erb
<h1 align="center">List of the Emoticons</h1>
<div id="emos"><%= render 'emos' %></div>

app/views/emoticons/index.js.erb
$("#emos").html("<%= escape_javascript(render("emos")) %>");

app/views/emoticons/new.html.erb

<%= render 'form' %>


app/views/emoticons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Emo:</b>
  <%= @emoticon.emo %>
</p>

<p>
  <b>Name:</b>
  <%= @emoticon.name %>
</p>t


<%= link_to 'Edit', edit_emoticon_path(@emoticon) %> |
<%= link_to 'Back', emoticons_path %>

app/views/home/about.html.erb
<% provide(:title, 'Contact') %>
<h2>What is an emoticon?</h2>
<p>
 <strong>Emoticon</strong> or <strong>Emoji</strong>; Japanese pronunciation: [emodʑi] is the Japanese term for the ideograms or smileys used in Japanese electronic messages and webpages. Originally meaning pictograph, the word literally means "picture" (e) + "letter" (moji). 
 <br><br>
 <h2>About this app</h2>
 <strong>Emosearch</strong> is a fun side project of <a href="http://www.arkavis.com/">Arkavis Siam</a>. <strong>Emosearch</strong> helps you to find the <strong>emoticons</strong> that match with your feeling (for example: for chatting).<br>
 Code : Desak Putu Pramesti Aldila Iswari <br>Logo Design : Sukrit Jitshob
</p>

app/views/home/index.html.erb
<div class="center hero-unit" >
	
    	<div align="center"><%= image_tag "logo_emo2.png", :alt => "Emosearch", :width => "600px", :class => "img-rounded" %></div><br>
       		<div align="center"><%= form_tag emoticons_path, :method => 'get', :id => "emos_search" do %>
               <p>
    			<%= text_field_tag :search, params[:search], :class => "span3", :placeholder => "  enter emotion - f.e. confused  " %>
   				<%#= submit_tag "Search", :name => nil %> 
  				</p>
			</div>
</div>
<div id="emos"></div>
<% end %>
		



app/views/layouts/_footer.html.erb
<footer class="footer">
    <a href="http://railstutorial.org/">Rails Project</a>
    by Aldila


  

  <div align="right">
 <ul class="inline">
      <li><%= link_to "About",  about_path %></li>

      <li><a href="http://www.arkavis.com/">Arkavis Siam</a></li>
</ul>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
        <div id="user_nav">
          <%= link_to "emosearch", welcomePage_path, :class => 'brand' %>

          <nav>
           <ul class="nav pull-right">
                <li><%= link_to "All Emoticons", emo_list_path %></li>
                <li><%= link_to "Suggest New Emoticon", add_emo_path %></li>
                <li><%= link_to "About",  about_path %></li>
          </nav>
        
        </div>
      </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EmoProjekt</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <script type="text/javascript" src="/assets/livesearch.js"></script>  
    <%= csrf_meta_tags %>
</head>
<body>

    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    <%= yield %>
   
  </div>

</body>
</html>

app/views/users/index.html.erb
<table>
  <tr>
    <th>Username</th>
  <!--   <th>Email</th>
    <th>Password digest</th>
    <th></th>
    <th></th>
    <th></th> -->
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
   <!--  <td><%= user.email %></td>
    <td><%= user.password_digest %></td> -->
    <td><%= link_to 'Show', user %></td>
  <!--   <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
  </tr>
<% end %>
</table>

<br />
<!-- 
<%= link_to 'New User', new_user_path %> -->

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>